### ISSUE TITLE
Is there a way to locate `RiotClientServices.exe` and  `system.yaml` manually?

### ISSUE THREAD

**Issue by BakaFT** [hawolt/Netherblade#53]
Using this tool on **Tencent server**(it's a lot different on RC/LCU dir tree strucuture with global server) 

or using it on a PC that reinstalled windows(**lost things under **%ALLUSERPROFILE%**) will get such error:

```bash
Unable to locate RiotClientServices.exe or system.yaml, exiting (1).
[22 Oct 2023 14:37:02] [ERROR] com.hawolt.util.LocaleInstallation::<clinit> java.io.FileNotFoundException
        at com.hawolt.util.LocaleInstallation.locateYaml(LocaleInstallation.java:61)
        at com.hawolt.util.LocaleInstallation.<clinit>(LocaleInstallation.java:29)
        at com.hawolt.yaml.LocalSystemYaml.generate(LocalSystemYaml.java:43)
        at com.hawolt.yaml.LocalSystemYaml.<clinit>(LocalSystemYaml.java:30)
        at com.hawolt.Main.main(Main.java:124)
shutdown on Thread[AWT-EventQueue-0,6,main]
```

It will be great if we can set/select the files need by hands.

**Comment by BakaFT** [comment]
maybe i can work on this, will reopen this issue if make any progress

**Comment by hawolt** [comment]
Feel free to work on this
